coreHotelRoomBookingAdminPortal/Controllers/HTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreHotelRoomBookingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace coreHotelRoomBookingAdminPortal.Controllers
{
    public class HTypeController : Controller
    {
        HotelAdminDbContext context;
    
        public HTypeController(HotelAdminDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index()
        {
            var hotelType = context.HotelTypes.ToList();
            return View(hotelType);
        }
        [HttpGet]
        public ViewResult Create()
        {
            //ViewBag.hotelType = new SelectList(context.HotelTypes, "HotelId", "HotelName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("HotelTypeName","HotelTypeDescription")] HotelType e1)
        {
            if (ModelState.IsValid)
            {
                context.HotelTypes.Add(e1);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(e1);
            
        }
        public ViewResult Details(int id)
        {
            HotelType hotelType = context.HotelTypes.Where(x => x.HotelTypeId == id).SingleOrDefault();
            return View(hotelType);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            HotelType hotelType = context.HotelTypes.Find(id);

            return View(hotelType);
        }

        [HttpPost]
        public ActionResult Delete(int id, HotelType e1)
        {
            var hotelType = context.HotelTypes.Where(x => x.HotelTypeId == id).SingleOrDefault();
            context.HotelTypes.Remove(hotelType);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            HotelType ud = context.HotelTypes.Where(x => x.HotelTypeId == id).SingleOrDefault();
            //ViewBag.hotelType = new SelectList(context.Hotels, "HotelId", "HotelName",ud.Hotels);
            return View(ud);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( int id , [Bind("HotelTypeName", "HotelTypeDescription")] HotelType e1)
        {
            if (ModelState.IsValid)
            {
                HotelType hotelType = context.HotelTypes.Where(x => x.HotelTypeId == id).SingleOrDefault();
            hotelType.HotelTypeName = e1.HotelTypeName;
            hotelType.HotelTypeDescription = e1.HotelTypeDescription;
            //context.Entry(hotelType).CurrentValues.SetValues(e1);
            context.SaveChanges();
            return RedirectToAction("Index");
            }
            return View(e1);
        }
    }
}

coreHotelRoomBookingAdminPortal/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreHotelRoomBookingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace coreHotelRoomBookingAdminPortal.Controllers
{
    public class HotelController : Controller
    {
        HotelAdminDbContext context;


        public HotelController(HotelAdminDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index()
        {
            var hotel = context.Hotels.ToList();
            return View(hotel);
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.hotelType = new SelectList(context.HotelTypes, "HotelTypeId", "HotelTypeName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Hotel e1)
        {
            context.Hotels.Add(e1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            Hotel hotel = context.Hotels.Where(x => x.HotelId == id).SingleOrDefault();
            return View(hotel);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            Hotel hotel = context.Hotels.Find(id);

            return View(hotel);
        }

        [HttpPost]
        public ActionResult Delete(int id, Hotel e1)
        {
            var hotel = context.Hotels.Where(x => x.HotelId == id).SingleOrDefault();
            context.Hotels.Remove(hotel);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Hotel ud = context.Hotels.Where(x => x.HotelId == id).SingleOrDefault();
            ViewBag.hotelType = new SelectList(context.HotelTypes, "HotelTypeId", "HotelTypeName");
            return View(ud);
        }

        [HttpPost]
        public ActionResult Edit(int id, Hotel h1)
        {
            Hotel hotel = context.Hotels.Where(x => x.HotelId == id).SingleOrDefault();
            
            hotel.HotelName = h1.HotelName;
            hotel.HotelAddress = h1.HotelAddress;
            hotel.HotelEmailId = h1.HotelEmailId;
            hotel.HotelDistrict = h1.HotelDistrict;
            hotel.HotelCity = h1.HotelCity;
            hotel.HotelState = h1.HotelState;
            hotel.HotelCountry = h1.HotelCountry;
            hotel.HotelContactNumber = h1.HotelContactNumber;
            hotel.HotelRating = h1.HotelRating;
            hotel.HotelImage = h1.HotelImage;
            hotel.HotelDescription = h1.HotelDescription;
            hotel.HotelTypeId = h1.HotelTypeId;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

coreHotelRoomBookingAdminPortal/Controllers/HotelRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreHotelRoomBookingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace coreHotelRoomBookingAdminPortal.Controllers
{
    public class HotelRoomController : Controller
    {
        HotelAdminDbContext context;

        public HotelRoomController(HotelAdminDbContext _context)
        {
            context = _context;
        }


        public IActionResult Index()
        {
            var hotelRoom = context.HotelRooms.ToList();
            return View(hotelRoom);
        }
        [HttpGet]

        public ViewResult Create()
        {
            ViewBag.hotel = new SelectList(context.Hotels, "HotelId", "HotelName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HotelRoom e1)
        {
            context.HotelRooms.Add(e1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            HotelRoom hotelRoom = context.HotelRooms.Where(x => x.RoomId == id).SingleOrDefault();
            return View(hotelRoom);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            HotelRoom hotelRoom = context.HotelRooms.Find(id);

            return View(hotelRoom);
        }

        [HttpPost]
        public ActionResult Delete(int id, HotelRoom e1)
        {
            var hotelRoom = context.HotelRooms.Where(x => x.RoomId == id).SingleOrDefault();
            context.HotelRooms.Remove(hotelRoom);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            HotelRoom ud = context.HotelRooms.Where(x => x.RoomId == id).SingleOrDefault();
            ViewBag.hotel = new SelectList(context.Hotels, "HotelId", "HotelName");
            return View(ud);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, HotelRoom e1)
        {
            HotelRoom hotelRoom = context.HotelRooms.Where(x => x.RoomId == id).SingleOrDefault();
            hotelRoom.RoomType = e1.RoomType;
            hotelRoom.RoomPrice = e1.RoomPrice;
            hotelRoom.RoomDescription = e1.RoomDescription;
            hotelRoom.RoomImage = e1.RoomImage;
            hotelRoom.HotelId = e1.HotelId;
            //context.Entry(hotelRoom).CurrentValues.SetValues(e1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

coreHotelRoomBookingAdminPortal/Controllers/RoomFacilityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreHotelRoomBookingAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace coreHotelRoomBookingAdminPortal.Controllers
{
    public class RoomFacilityController : Controller
    {
        HotelAdminDbContext context;
    
        public RoomFacilityController(HotelAdminDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index()
        {
            var roomFacilities = context.RoomFacilities.ToList();
            return View(roomFacilities);
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.hotelRoom = new SelectList(context.HotelRooms, "RoomId", "RoomType");
            return View();
        }
        [HttpPost]
        public ActionResult Create(RoomFacility e1)
        {
            try
            {
                context.RoomFacilities.Add(e1);
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            RoomFacility roomFacility = context.RoomFacilities.Where(x => x.RoomFacilityId == id).SingleOrDefault();
            return View(roomFacility);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            RoomFacility roomFacility = context.RoomFacilities.Find(id);

            return View(roomFacility);
        }

        [HttpPost]
        public ActionResult Delete(int id, RoomFacility e1)
        {
            var facility = context.RoomFacilities.Where(x => x.RoomFacilityId == id).SingleOrDefault();
            context.RoomFacilities.Remove(facility);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            RoomFacility ud = context.RoomFacilities.Where(x => x.RoomFacilityId == id).SingleOrDefault();
            ViewBag.hotelRoom = new SelectList(context.HotelRooms, "RoomId", "RoomType",ud.RoomId);
            return View(ud);
        }

        [HttpPost]
        public ActionResult Edit(int id, RoomFacility e1)
        {
            RoomFacility hotelRoom = context.RoomFacilities.Where(x => x.RoomFacilityId == id).SingleOrDefault();
            hotelRoom.IsAvilable = e1.IsAvilable;
            hotelRoom.Wifi = e1.Wifi;
            hotelRoom.AirConditioner = e1.AirConditioner;
            hotelRoom.Ekettle = e1.Ekettle;
            hotelRoom.Refrigerator = e1.Refrigerator;
            hotelRoom.RoomFacilityDescription = e1.RoomFacilityDescription;

            //context.Entry(hotelRoom).CurrentValues.SetValues(e1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

coreHotelRoomBookingAdminPortal/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http;
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Room Booking - Admin</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Starter.css" />
</head>
<body>



    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" asp-controller="Home"  asp-action="HomeNew">Hotel Room Booking</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="HType"  asp-action="Index">Hotel Type</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Hotel">Hotel</a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="HotelRoom">Hotel Room</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="RoomFacility">Room Facility</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <label class="form-control">
                    Welcome @Context.Session.GetString("uname")!!
                </label>
                &nbsp;&nbsp;
                    <a class="btn btn-outline-success my-2 my-sm-0" asp-action="Logout" asp-controller="Account">Logout</a>
            </form>
        </div>
    </nav>


    <main role="main" class="container">

        
            @RenderBody()
        
        <hr/>
    </main>


    <footer class="container">
        <p>&copy; JAAM</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

coreHotelRoomBookingAdminPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - coreHotelRoomBookingAdminPortal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">coreHotelRoomBookingAdminPortal</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - coreHotelRoomBookingAdminPortal</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

coreHotelRoomBookingAdminPortal/Views/Shared/_UserLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Http;

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Room Booking - Admin</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Starter.css" />
</head>
<body>



    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" asp-controller="Home" asp-action="HomeNew">Hotel Room Booking</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="HType" asp-action="Index">Hotel Type</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Hotel">Hotel</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="HotelRoom">Hotel Room</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="RoomFacility">Room Facility</a>
                </li>
            </ul>
        </div>
    </nav>


    <main role="main" class="container">


        @RenderBody()

        <hr />
    </main>


    <footer class="container">
        <p>&copy; JAAM</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>